development:
  adapter: postgresql
  encoding: unicode
  database: linklove_app_development
  pool: 5
  host: localhost
  username: matthewthees
  password:
  cucumber:

test:
  adapter: postgresql
  encoding: unicode
  database: linklove_app_test
  pool: 5
  host: localhost
  username: matthewthees
  password:
  cucumber:

